name: Build and Attest

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build your website
      - run: |
          mkdir -p dist
          cp -r * dist/

      # Generate artifact attestation
      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: dist/**
